services:
  postgres:
    image: library/postgres:9.5.21-alpine
    container_name: authify-db
    environment:
      POSTGRES_DB: authify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - authify-postgres:/var/lib/postgresql/data
    ports:
      - 31684:5432
  redis:
    image: library/redis:4.0.8-alpine
    container_name: authify-redis
    ports:
      - 40139:6379
    volumes:
      - authify-redis:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  authify-postgres:
  authify-redis: