spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAX_POOL_SIZE}
  web:
    resources:
      add-mappings: false
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: none
              create-target: src/main/resources/db/diff.sql
  liquibase:
    enabled: false
    change-log: db/changelog.yaml
  docker:
    compose:
      enabled: false

logging:
  level:
    com.authify: DEBUG
