spring:
  datasource:
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: update
  liquibase:
    enabled: true
  docker:
    compose:
      enabled: true